apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset
  labels:
    app_name: appli
    tier: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: app
          image: registry.cluster.wik.cloud/public/echo
